### ISSUE TITLE
unpublish extension from vscode marketplace

### ISSUE THREAD

**Issue by ssbarnea** [spinosae/vscode-ansible-vault#6]
In order to avoid avoid confusing Ansible users looking for vscode extensions, could you be so kind to un publish this extension from the marketplace? Now there is an actively maintained community extension that includes the vaulting features: https://marketplace.visualstudio.com/items?itemName=zbr.vscode-ansible 

Note: there is no need to "delete" extension from marketplace, using "unpublish" is enough in order to hide extension from normal searches, an action that is also reversible (as opposed to delete).

**Comment by FlorianLaunay** [comment]
Hi @spinosae. Could you please take a look ? Microsoft indicates in its documentation that it is possible to unpublish : https://code.visualstudio.com/api/working-with-extensions/publishing-extension#unpublishing-extensions

**Comment by spinosae** [comment]
@ssbarnea @FlorianLaunay I've unpublished the extension. Thanks for the good community work!
